name: Java CI with Maven and Docker

on:
  push:
    branches:
      - master  # Виконувати на пуші в гілку master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Встановлюємо JDK та Maven
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Крок 3: Збираємо артефакт через Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Крок 4: Завантажуємо JAR-файл як артефакт
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-jar
          path: target/helloworld-1.0-SNAPSHOT.jar

      # Крок 5: Логін в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Крок 6: Створення Docker образу
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/my-java-app:${{ github.sha }} .

      # Крок 7: Публікація Docker образу в GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.actor }}/my-java-app:${{ github.sha }}
